import type { CategoryInterface } from '@/interfaces/CategoryInterface';

const now = new Date();

export const categorySeeder: CategoryInterface[] = [
  // User 2 (Alex)
  {
    id: 1,
    name: 'Salary',
    color: '#16A34A',
    type: 'income',
    createdAt: now,
    updatedAt: now,
    userId: 2,
    transactionIds: [1],
  },
  {
    id: 2,
    name: 'Groceries',
    color: '#F97316',
    type: 'expense',
    createdAt: now,
    updatedAt: now,
    userId: 2,
    transactionIds: [2],
  },
  {
    id: 3,
    name: 'Rent',
    color: '#0EA5E9',
    type: 'expense',
    createdAt: now,
    updatedAt: now,
    userId: 2,
    transactionIds: [3],
  },
  {
    id: 4,
    name: 'Subscriptions',
    color: '#6366F1',
    type: 'expense',
    createdAt: now,
    updatedAt: now,
    userId: 2,
    transactionIds: [4],
  },
  {
    id: 5,
    name: 'Savings',
    color: '#22C55E',
    type: 'transfer',
    createdAt: now,
    updatedAt: now,
    userId: 2,
    transactionIds: [8, 10],
  },
  // User 3 (Maria)
  {
    id: 6,
    name: 'Salary',
    color: '#16A34A',
    type: 'income',
    createdAt: now,
    updatedAt: now,
    userId: 3,
    transactionIds: [5],
  },
  {
    id: 7,
    name: 'Groceries',
    color: '#F97316',
    type: 'expense',
    createdAt: now,
    updatedAt: now,
    userId: 3,
    transactionIds: [6],
  },
  {
    id: 8,
    name: 'Subscriptions',
    color: '#6366F1',
    type: 'expense',
    createdAt: now,
    updatedAt: now,
    userId: 3,
    transactionIds: [7],
  },
  {
    id: 9,
    name: 'Savings',
    color: '#22C55E',
    type: 'transfer',
    createdAt: now,
    updatedAt: now,
    userId: 3,
    transactionIds: [11],
  },
  // User 4 (Daniel)
  {
    id: 10,
    name: 'Groceries',
    color: '#F97316',
    type: 'expense',
    createdAt: now,
    updatedAt: now,
    userId: 4,
    transactionIds: [9],
  },
  {
    id: 11,
    name: 'Savings',
    color: '#22C55E',
    type: 'transfer',
    createdAt: now,
    updatedAt: now,
    userId: 4,
    transactionIds: [12],
  },
];
