import type { GoalInterface } from '@/interfaces/GoalInterface';
import { GoalStatusHelper } from '@/utils/GoalStatusHelper';

const now = new Date();

export const goalSeeder: GoalInterface[] = [
  {
    id: 1,
    name: 'Emergency fund',
    description: 'Save 3 months of living expenses.',
    targetAmount: 3000,
    currentAmount: 1200,
    startDate: new Date(now.getFullYear(), now.getMonth() - 5, 1),
    endDate: new Date(now.getFullYear(), now.getMonth() + 1, 1),
    status: GoalStatusHelper.compute(1200, 3000),
    createdAt: now,
    updatedAt: now,
    userId: 5,
    transactionIds: [8, 10],
  },
  {
    id: 2,
    name: 'Europe Vacation',
    description: '2-week trip through Spain and Italy.',
    targetAmount: 4000,
    currentAmount: 1200,
    startDate: new Date(now.getFullYear(), now.getMonth() - 4, 1),
    endDate: new Date(now.getFullYear(), now.getMonth() + 4, 1),
    status: GoalStatusHelper.compute(1200, 4000),
    createdAt: now,
    updatedAt: now,
    userId: 5,
    transactionIds: null,
  },
  {
    id: 3,
    name: 'New Car',
    description: 'Family SUV',
    targetAmount: 15000,
    currentAmount: 8500,
    startDate: new Date(now.getFullYear(), now.getMonth() - 6, 10),
    endDate: new Date(now.getFullYear(), now.getMonth() + 10, 10),
    status: GoalStatusHelper.compute(8500, 15000),
    createdAt: now,
    updatedAt: now,
    userId: 5,
    transactionIds: null,
  },
  {
    id: 4,
    name: 'New laptop',
    description: 'Save for a new work laptop.',
    targetAmount: 1500,
    currentAmount: 1500,
    startDate: new Date(now.getFullYear(), now.getMonth() - 3, 15),
    endDate: new Date(now.getFullYear(), now.getMonth() - 1, 15),
    status: GoalStatusHelper.compute(1500, 1500),
    createdAt: now,
    updatedAt: now,
    userId: 5,
    transactionIds: null,
  },
  {
    id: 5,
    name: 'Investment Course',
    description: 'Advanced personal finance course.',
    targetAmount: 800,
    currentAmount: 400,
    startDate: new Date(now.getFullYear(), now.getMonth() - 1, 1),
    endDate: new Date(now.getFullYear(), now.getMonth() + 2, 1),
    status: GoalStatusHelper.compute(400, 800),
    createdAt: now,
    updatedAt: now,
    userId: 5,
    transactionIds: null,
  },
  {
    id: 6,
    name: 'Wedding Gift',
    description: 'Gift for sister’s wedding.',
    targetAmount: 500,
    currentAmount: 100,
    startDate: new Date(now.getFullYear(), now.getMonth(), 1),
    endDate: new Date(now.getFullYear(), now.getMonth() + 1, 1),
    status: GoalStatusHelper.compute(100, 500),
    createdAt: now,
    updatedAt: now,
    userId: 5,
    transactionIds: null,
  },
];
