import type { TransactionInterface } from '@/interfaces/TransactionInterface';

const now = new Date();

export const transactionSeeder: TransactionInterface[] = [
  {
    id: 1,
    amount: 3200,
    description: 'Monthly salary',
    date: new Date(now.getFullYear(), now.getMonth(), 1),
    createdAt: now,
    updatedAt: now,
    userId: 2,
    categoryId: 1,
    goalId: null,
  },
  {
    id: 2,
    amount: -120,
    description: 'Groceries - supermarket',
    date: new Date(now.getFullYear(), now.getMonth(), 3),
    createdAt: now,
    updatedAt: now,
    userId: 2,
    categoryId: 2,
    goalId: null,
  },
  {
    id: 3,
    amount: -900,
    description: 'Monthly rent',
    date: new Date(now.getFullYear(), now.getMonth(), 5),
    createdAt: now,
    updatedAt: now,
    userId: 2,
    categoryId: 3,
    goalId: null,
  },
  {
    id: 4,
    amount: -15,
    description: 'Music streaming subscription',
    date: new Date(now.getFullYear(), now.getMonth(), 7),
    createdAt: now,
    updatedAt: now,
    userId: 2,
    categoryId: 4,
    goalId: null,
  },
  {
    id: 5,
    amount: 2800,
    description: 'Monthly salary',
    date: new Date(now.getFullYear(), now.getMonth(), 1),
    createdAt: now,
    updatedAt: now,
    userId: 3,
    categoryId: 6,
    goalId: null,
  },
  {
    id: 6,
    amount: -90,
    description: 'Groceries - local market',
    date: new Date(now.getFullYear(), now.getMonth(), 4),
    createdAt: now,
    updatedAt: now,
    userId: 3,
    categoryId: 7,
    goalId: null,
  },
  {
    id: 7,
    amount: -20,
    description: 'Video streaming subscription',
    date: new Date(now.getFullYear(), now.getMonth(), 9),
    createdAt: now,
    updatedAt: now,
    userId: 3,
    categoryId: 8,
    goalId: null,
  },
  {
    id: 8,
    amount: -300,
    description: 'Transfer to savings - emergency fund',
    date: new Date(now.getFullYear(), now.getMonth(), 10),
    createdAt: now,
    updatedAt: now,
    userId: 2,
    categoryId: 5,
    goalId: 1,
  },
  {
    id: 9,
    amount: -150,
    description: 'Groceries - weekend shopping',
    date: new Date(now.getFullYear(), now.getMonth(), 12),
    createdAt: now,
    updatedAt: now,
    userId: 4,
    categoryId: 10,
    goalId: null,
  },
  {
    id: 10,
    amount: -200,
    description: 'Transfer to savings - emergency fund',
    date: new Date(now.getFullYear(), now.getMonth(), 15),
    createdAt: now,
    updatedAt: now,
    userId: 2,
    categoryId: 5,
    goalId: 1,
  },
  {
    id: 11,
    amount: -250,
    description: 'Transfer to savings - new laptop',
    date: new Date(now.getFullYear(), now.getMonth(), 18),
    createdAt: now,
    updatedAt: now,
    userId: 3,
    categoryId: 9,
    goalId: 2,
  },
  {
    id: 12,
    amount: -400,
    description: 'Transfer to savings - vacation trip',
    date: new Date(now.getFullYear(), now.getMonth(), 20),
    createdAt: now,
    updatedAt: now,
    userId: 4,
    categoryId: 11,
    goalId: 3,
  },

  // User 5 (John)
  {
    id: 13,
    amount: 3500,
    description: 'Monthly salary',
    date: new Date(now.getFullYear(), now.getMonth(), 1),
    createdAt: now,
    updatedAt: now,
    userId: 5,
    categoryId: 12,
    goalId: null,
  },
  {
    id: 14,
    amount: -140,
    description: 'Groceries - supermarket',
    date: new Date(now.getFullYear(), now.getMonth(), 2),
    createdAt: now,
    updatedAt: now,
    userId: 5,
    categoryId: 13,
    goalId: null,
  },
  {
    id: 15,
    amount: -18,
    description: 'Streaming subscription',
    date: new Date(now.getFullYear(), now.getMonth(), 8),
    createdAt: now,
    updatedAt: now,
    userId: 5,
    categoryId: 14,
    goalId: null,
  },
  {
    id: 16,
    amount: -250,
    description: 'Transfer to savings - emergency fund',
    date: new Date(now.getFullYear(), now.getMonth(), 11),
    createdAt: now,
    updatedAt: now,
    userId: 5,
    categoryId: 15,
    goalId: 1,
  },

  // User 6 (Jane)
  {
    id: 17,
    amount: 3100,
    description: 'Monthly salary',
    date: new Date(now.getFullYear(), now.getMonth(), 1),
    createdAt: now,
    updatedAt: now,
    userId: 6,
    categoryId: 16,
    goalId: null,
  },
  {
    id: 18,
    amount: -95,
    description: 'Groceries - local market',
    date: new Date(now.getFullYear(), now.getMonth(), 6),
    createdAt: now,
    updatedAt: now,
    userId: 6,
    categoryId: 17,
    goalId: null,
  },
  {
    id: 19,
    amount: -220,
    description: 'Transfer to savings - wedding gift',
    date: new Date(now.getFullYear(), now.getMonth(), 16),
    createdAt: now,
    updatedAt: now,
    userId: 6,
    categoryId: 18,
    goalId: 6,
  },
];
