import type { UserInterface } from '@/interfaces/UserInterface';

export const userSeeder: UserInterface[] = [
  {
    id: 1,
    name: 'Admin User',
    email: 'admin@fintrack.local',
    password: 'admin123',
    role: 'admin',
    createdAt: new Date(),
    updatedAt: new Date(),
    transactionIds: [],
    goalIds: null,
  },
  {
    id: 2,
    name: 'Alex Johnson',
    email: 'alex.johnson@fintrack.local',
    password: 'password123',
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
    transactionIds: [1, 2, 3, 4, 8, 10],
    goalIds: [1],
  },
  {
    id: 3,
    name: 'Maria Lopez',
    email: 'maria.lopez@fintrack.local',
    password: 'password123',
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
    transactionIds: [5, 6, 7, 11],
    goalIds: [2],
  },
  {
    id: 4,
    name: 'Daniel Kim',
    email: 'daniel.kim@fintrack.local',
    password: 'password123',
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
    transactionIds: [9, 12],
    goalIds: [3],
  },
];
