// author: Santiago Gómez
import type { UserInterface } from '@/modules/user/interfaces/UserInterface';

const now = new Date();

export const userSeeder: UserInterface[] = [
  {
    id: 1,
    name: 'Admin User',
    email: 'admin@fintrack.local',
    password: 'admin123',
    role: 'admin',
    createdAt: new Date(now.getFullYear(), now.getMonth() - 6, 1),
    updatedAt: now,
    categoryIds: null,
    goalIds: null,
    transactionIds: [],
  },
  {
    id: 2,
    name: 'Alex Johnson',
    email: 'alex.johnson@fintrack.local',
    password: 'password123',
    role: 'user',
    createdAt: new Date(now.getFullYear(), now.getMonth() - 6, 5),
    updatedAt: now,
    categoryIds: [1, 2, 3, 4, 5],
    goalIds: [1, 2, 3],
    transactionIds: [1, 2, 3, 4, 8, 10],
  },
  {
    id: 3,
    name: 'Maria Lopez',
    email: 'maria.lopez@fintrack.local',
    password: 'password123',
    role: 'user',
    createdAt: new Date(now.getFullYear(), now.getMonth() - 4, 12),
    updatedAt: now,
    categoryIds: [6, 7, 8, 9],
    goalIds: [4],
    transactionIds: [5, 6, 7, 11],
  },
  {
    id: 4,
    name: 'Daniel Kim',
    email: 'daniel.kim@fintrack.local',
    password: 'password123',
    role: 'user',
    createdAt: new Date(now.getFullYear(), now.getMonth() - 2, 20),
    updatedAt: now,
    categoryIds: [10, 11],
    goalIds: [5],
    transactionIds: [9, 12],
  },
  {
    id: 5,
    name: 'John Doe',
    email: 'john@email.com',
    password: 'password123',
    role: 'user',
    createdAt: new Date(now.getFullYear(), now.getMonth() - 1, 14),
    updatedAt: now,
    categoryIds: [12, 13, 14, 15],
    goalIds: [7, 8],
    transactionIds: [13, 14, 15, 16],
  },
  {
    id: 6,
    name: 'Jane Smith',
    email: 'jane@email.com',
    password: 'password123',
    role: 'user',
    createdAt: new Date(now.getFullYear(), now.getMonth(), 1),
    updatedAt: now,
    categoryIds: [16, 17, 18],
    goalIds: [6],
    transactionIds: [17, 18, 19],
  },
];
